[workspace]
authors = ["toohuman <michael.crosscombe@proton.me>"]
channels = ["conda-forge"]
name = "jax-ant-arena"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
visualise = "python simulation/visualise_sim.py"
visualize = "python simulation/visualise_sim.py"
animate = "python simulation/animate_sim.py"
batch-runner = "python simulation/batch_run.py"

setup-gpu = "pip install --upgrade 'jax[cuda12]' -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"

[dependencies]
python = ">=3.13.3,<3.14"
matplotlib = ">=3.10.1,<4"
pyqt = ">=5.15.10,<6"
tqdm = ">=4.67.1,<5"
hydra-core = ">=1.3.2,<2"
omegaconf = ">=2.3.0,<3"


# Platform-specific dependencies
[target.linux-64.dependencies]
pip = "*"

# Platform-specific dependencies
[target.osx-arm64.dependencies]
jax = "*"
jaxlib = "*"

