[workspace]
authors = ["toohuman <michael.crosscombe@proton.me>"]
channels = ["conda-forge"]
name = "jax-ant-arena"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
visualise = "python simulation/visualise_sim.py"
visualize = "python simulation/visualise_sim.py"
animate = "python simulation/animate_sim.py"
batch-runner = "python simulation/batch_run.py"

setup-gpu = "pip install --upgrade 'jax[cuda12]' -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"

[dependencies]
python = ">=3.13.5,<3.14"
matplotlib = ">=3.10.3,<4"
pyqt = ">=5.15.11,<6"
tqdm = ">=4.67.1,<5"
hydra-core = ">=1.3.2,<2"
omegaconf = ">=2.3.0,<3"
pandas = ">=2.3.0,<3"
seaborn = ">=0.13.2,<0.14"
scipy = ">=1.15.2,<2"
networkx = ">=3.5,<4"
scikit-learn = ">=1.7.0,<2"


# Platform-specific dependencies
[target.linux-64.dependencies]
pip = "*"

# Platform-specific dependencies
[target.osx-arm64.dependencies]
jax = "*"
jaxlib = "*"

[feature.dev.dependencies]
nodejs = ">=18"
jupyter = ">=1.1.1,<2"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

